---
# See https://github.com/jvautier/project-cli
fullname: jvautier/ansible-role-python
description: Install python and python utilities through ansible
tags:
  - ansible
  - ansible-role
  - python
github: {}
