---
- name: install - required packages
  apt:
    name: "{{ package_name_python }}"
    state: present
  loop_control:
    loop_var: package_name_python
  loop:
    - python-dev
    - python-setuptools
    - python3-dev
    - python3
    - python3-pip
